[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_program = "7TgnvEJ3UWAfuVsJJd7Ld5Ued2kcn5MEfbjmMXXAgsTQ"
movie-program = "CwzfT7dsqVYhwLc8jXut9nrTNtAaHrUzuQky7My9BS1z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
